# Credit to Dean Attali for his 'Beautiful Jekyll' theme.

### COLLECTIONS
collections:
  documentation:
    output: true
    permalink: /:collection/:name
  team:
    output: false


### REQUIRED OPTIONS
# Can be text or img
# title: WCRL
title-img: "/assets/img/wcrl_simple_logo.png"

# Author Name for Footer
author: Octobot

# Socials
social-network-links:
  github: wcrl
  youtube: "channel/UCIaK69JDDWl9wAELpbH6m2w"
  instagram: wcrl_binghamton
  discord: "rwarHRtmhz"
  # email: "someone@example.com"
  # facebook: username


### GENERAL OPTIONS
# Adds website link to footer (you can remove)
url-pretty: "wcrl.github.io"

# Add the website title to the title of every page
title-on-all-pages: true

# Add a search button to the navbar
post_search: true

# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
# If this setting is off, then long sub-menu words might get cut off
# See https://github.com/daattali/beautiful-jekyll/issues/765 to understand the issue this setting can solve
navbar-var-length: false

# The keywords to associate with your website, for SEO purposes
keywords: "Binghamton,Combat Robotics,WCRL,Robotics,Engineering,Club,Organization"


### CUSTOMIZATION
# Colors
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
site-css:
 - "/assets/css/sidebar.css"
 - "/assets/css/card.css"

# If you have common JavaScript files that should be included in every page, list them here
site-js:
 - "/assets/js/sidebar.js"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"


### ADVANCED SETTINGS
# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
# paginate: 0

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap